[env]
PORT = "8080"

[build]
# Dockerfile is used automatically

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100

[service]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
